# relative paths from this config
file_path: "data/raw_data_healthcare.csv"
preprocessing_path: "data/preprocessed.csv"
phrase_path: "data/phrase.csv"
sent_phrase_path: "data/sent_analysis.csv"

# list of diseases that should be included, if empty all will be taken into account
diseases:
  - "Crohn's Disease"
  - "Ulcerative Colitis"

# list of treatments that should be included, if empty all will be taken into account
treatments: 

# list of antibodies that should be included, if empty all will be taken into account
antibodies:

# phrase extraction parameters
min_length: 3
max_length: 12

# list of broad topics that should be taken into account
topics:
  - "effect"
  - "price"
  - "frequency"
