# relative paths from this config
file_path: "data/raw_data_healthcare.csv"
preprocessing_path: "data/preprocessed.csv"
keywords_output_file_path: "data/data_with_keywords.csv"
preprocessing_config_file: "data_preprocessing/config.yaml"
similarity_scores_path: "data/topic_similarity_scores"

# list of diseases that should be included, if empty all will be taken into account
diseases:
  - "Crohn's Disease"
  - "Ulcerative Colitis"

# list of treatments that should be included, if empty all will be taken into account
treatments: 

# list of antibodies that should be included, if empty all will be taken into account
antibodies:

# list of broad topics that should be taken into account
topics:
  - "symptoms, side effects"
  - "price"
  - "health improvements"


# do dictionary 