file_path: "./data_preprocessing/data/raw_data_healthcare.csv"
output_path: "./data_preprocessing/preprocessed.csv"

diseases:
  - "Crohn's Disease"
  - "Ulcerative Colitis"

treatments:


antibodies:


